id: I3BECEFFB
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:17:23.622583
last_modified: 2023-02-10 00:17:23.622707
source_metadata:
  title: 'MSV 6,08: Kathāvastu'
  language: bo
bases:
  BACE:
    base_file: BACE.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
